
import { Inter } from "next/font/google";
import "../styles/global.css";
import Sidebar from "@/components/sidebar"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen w-full bg-slate-100">
          <Sidebar />
          <div className="flex flex-col w-full h-full ml-64 p-4 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

